# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl: 
title: Grokkin' Kotlin
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: (aka "Yet Another Blog Charting My Learning")
author: Andrew Harmel-Law
email: andrew [at] harmel-law [dot] com
description: A blog about the things I learn, and the thoughts I have, as I learn Kotlin.
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /posts/:categories/:year/:month/:day/:title.html
timezone: UK/London
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src
